name: ecoder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - numba
    - numpy
    - pandas
    - matplotlib
    - pillow
    - jupyter
    - tensorflow
    - keras
    - tensorflow-model-optimization
    - pot
    - mplhep
